version: '3'
services:
  auth:
    build:
      context: ./apps/auth/
      dockerfile: Dockerfile.dev
      args:
        JAR_FILE: auth.jar
    image: dpe/auth:0.0.1
    ports:
      - 8081:8080
      - 8051:8010
  dpe-core:
    build:
      context: ./apps/dpe-core/
      dockerfile: Dockerfile.dev
      args:
        JAR_FILE: dpe-core.jar
    image: dpe/dpe-core:0.0.1
    ports:
      - 8082:8080
      - 8052:8010